GET http://localhost:3001/api/test

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"Travis",
    "password":"password"
}

###

POST http://localhost:3001/api/register
Content-Type: application/json

{
    "username":"Gabe",
    "password":"password123"
}